import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter_reactive_ble/flutter_reactive_ble.dart';
import 'package:flutter_reactive_ble_example/src/ui/SQFLITE/sqldb.dart';
SqlDb sqlDb = SqlDb();
late int response;
late int response1;
late int meterTable;
bool isFunctionCalled = false;
int maxOutputLength = 72*3;
List<int> previousEventData = [];
// electric data
num clientID = 0;
num totalReading = 0;
num pulses = 0;
num totalCredit = 0;
num currentTarrif = 0;
num tarrifVersion = 0;
num valveStatus = 0;
num leackageFlag = 0;
num fraudFlag = 0;
num fraudHours = 0;
num fraudMinutes = 0;
num fraudDayOfWeek = 0;
num fraudDayOfMonth = 0;
num fraudMonth = 0;
num fraudYear = 0;
num totalDebit = 0;
num currentConsumption = 0;
num lcHour = 0;
num lcMinutes = 0;
num lcDayWeek = 0;
num lcDayMonth = 0;
num lcMonth = 0;
num lcYear = 0;
num  lastChargeValueNumber = 0;
num month1 = 0;
num month2 = 0;
num month3 = 0;
num month4 = 0;
num month5 = 0;
num month6 = 0;
num warningLimit = 0;
num checkSum = 0;
int sum = 0;
num test = 89;
//water data

num clientIDWater = 0;
num pulsesWater = 0;
num totalCreditWater = 0;
num currentTarrifWater = 0;
num tarrifVersionWater = 0;
num valveStatusWater = 0;
num leackageFlagWater = 0;
num fraudFlagWater = 0;
num fraudHoursWater = 0;
num fraudMinutesWater = 0;
num fraudDayOfWeekWater = 0;
num fraudDayOfMonthWater = 0;
num fraudMonthWater = 0;
num fraudYearWater = 0;
num totalDebitWater = 0;
num currentConsumptionWater = 0;
num lcHourWater = 0;
num lcMinutesWater = 0;
num lcDayWeekWater = 0;
num lcDayMonthWater = 0;
num lcMonthWater = 0;
num lcYearWater = 0;
num lastChargeValueNumberWater = 0;
num month1Water = 0;
num month2Water = 0;
num month3Water = 0;
num month4Water = 0;
num month5Water = 0;
num month6Water = 0;
num warningLimitWater = 0;
num checkSumWater = 0;
late DateTime currentTime;
final deviceName = TextEditingController();
int valU = 1;
String electricSN = ' ';
String waterSN = ' ';
String type = 'Electricity';
bool isDeviceFound = false;
late String meterName;
late DiscoveredDevice dataStored;
late String id;
late TextEditingController textEditingController;
dynamic name;
dynamic meterType;
late Timer timer;
int count = 0;
dynamic paddingType;