name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.1.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth & Device Communication
  flutter_reactive_ble: ^5.1.1

  # Data Handling & Storage
  collection: ^1.15.0
  get_storage: ^2.1.1
  sqflite_sqlcipher: ^2.2.1

  # State Management & Dependency Injection
  get: ^4.6.6
  provider: ^6.0.1

  # UI & Design Enhancements
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.64.0
  flutter_custom_clippers: ^2.1.0

  # User Interaction & Permissions
  flutter_barcode_scanner: ^2.0.0
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1

  # Utilities & Tools
  flutter_localizations:
    sdk: flutter
  functional_data: ^1.0.0
  intl: ^0.18.1
  path: ^1.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.1.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/